### PR TITLE
Add first implemetation of a command line interface(CLI)

### PR DESCRIPTION
**Pull request by broeder-j**
This is a first layout with first commands implemented including:
- data fleurinp list: query db for fleurinp
- data fleurinp cat: cat a certain file, usually inp.xml
- plot: exposing plot_fleur
- data structure import: import structure from inp.xml
- data parameter import
- workflow res: print all content of all Dict outputs of a process
- workflow inputdict: print content of all Dict inputs of a process

A further command group is
- aiida-fleur launch <workflow/calcjob>
which should be able to launch any aiida-fleur workchain from the command line.

A structure input can also be given as a file in any common structure format handable by ase.
i.e
- aiida-fleur launch inpgen -s ~/Desktop/1533724.cif
also works.

The base command group is aiida-fleur.
bash completion can be done with eval "$(_AIIDA_FLEUR_COMPLETE=source aiida-fleur)"
There is yet no documentation, no CI tests, no similiar check as in aiida-core.
Futher launch commands for all workchains and calcjob classes should be implemented.

Solves issue #14 

This is not done yet, I put it here for feedback and suggestions. Let me know what commands you would need in you daily work.

### CODE REVIEW

**Comment by broeder-j** [comment]
@anoopkcn and @Tseplyaev let me know what you think and what utilities you need.
for example checkout ```aiida-fleur plot --bokeh <pk>``` or ```aiida-fleur plot --bokeh -f <filename>```

**Comment by broeder-j** [comment]
there is a ```verdi process watch`` command, if we log or report in a certain way one might be able to create a command which plots certain information while complex workflows are running to understand better what is going on.

**Comment by broeder-j** [comment]
I currently find it hard/time consuming to track back what exactly happened, i.e which handlers where trickered, what was restarted how, what was cached.

**Comment by Tseplyaev** [comment]
I think I have come up with several suggestions:
1. Fleurinp: print out symmetries since they are bound to k-mesh
2. FleurinpModifier: in general the modification of an existing Fleurinp could be implemented as cdm options
3. About handlers/automatic restart: I think ``verdi process status`` prints out enough information to analyse what happened and there is no need to implement similar methods
4. Some methods that automatically generate inputs to continue a workchain. For example, If SCF failed due to time/iteration limits (but was converging), one wants to continue the SCF. That would be much easier to just type-in ``aiida-fleur generate inputs --from (workchain_pk)`` which returns required inputs and some info on how to modify and use it. Please refer to the figure below for details: for some reason user decides to continue converging SCF 1. For this he/she needs to not only gather basically the same input Dicts and Codes, but also find the corresponding RemoteFolder in the SCF 1 which is not user friendly. Hence that would be nice to have a method that prepares an input dict from SCF 1: it gathers the same Fleur Code, input Dicts and also adds RemoteFolder from the last FleurCalculation. Of course we should give a user a chance to modify input parameters - I would call this cdm option as a 'builder'. Such kind of cdm options would be very helpful for all of the workchains: EOS - to add new volumes; Relax - to continue from partly relaxed structure; magnetic workchains - to perform force theorem calculations starting from already converged reference; CreateMagnetic - to start from any place from EOS to final generation of the magnetic structure.

Screenshot 2020-10-27 at 09 34 47

**Comment by broeder-j** [comment]
1. is easy I will add this, because I will add an option to run this through spglib and get the sym group, number and  ggf other information.
Overall, I do not want to add to much of these, since you can already do this with:
```aiida-fleur data fleurinp cat <pk> | grep -i3 symOp``` or with ```aiida-fleur data fleurinp cat <pk> | grep row-```
Since we can ```cat``` any file in fleurinp, one can just grep for everything.

2. With this I also agree, Fleurinpmodifier is also meant to be used interactively for example in ipython. Through, I currently do not see how to best expose the whole Fleurinpmodifier functionality in one command. Or do we just expose a fixed small set of cases on the cli that people often want to do?

3. Thanks, you are right, I forgot about it.

4. Would first have to be designed and implemented as an internal function/tool also with choice to keep the provenance.
Which interface we then expose on the command line.
I like this idea to give the user power to clean up 'per hand' on failed stuff.
In general for this one should also disable (certain) failed calculation as valid caches. ;-)

**Comment by broeder-j** [comment]
@Tseplyaev @anoopkcn 
So I implemented the first set of launch commands, some workchains are still missing, and some reasonable defaults. 
You may like the feature that one can provide the structure in any common format.
i.e aiida-fleur launch scf -s ~/Desktop/1533724.cif
also works.

If you are fine with this. I can merge this soon.
Feedback of you on the naming conventions of options, see aiida_fleur/cmdline/util/options.py ,
would be nice, since this is an essential part of the user command line interface, which should be fixed and not changed if possible.

**Comment by broeder-j** [comment]
I will merge this now, since it also increases the test coverage by 14%

**Pull request merged**
