### PR TITLE
Changes necessary for aiida-core 2.0

### PR DESCRIPTION
**Pull request by janssenhenning**

### CODE REVIEW

**Comment by broeder-j** [comment]
@janssenhenning Is this complete, since the precommit is happy now? What was the issue with 'is_code'? It is not used currently. But I imagine it still to be useful for the commandline interface. The purpose was to allow users to provide a code in any posible way.

**Comment by janssenhenning** [comment]
I think this was a mistake by me I mistook the error the test gave me It is something in the test of is_code that has to be changed. 'is_code' should work fine. But the question is what is the difference between this function and load_code in aiida-core? This will also work with pks, uuids, and labels

**Comment by janssenhenning** [comment]
There is some issue with the archives used for some tests (test_plot and test_workflow_cmd). They fail when they are migrated to the newer version. But for the plugin itself I could not find any more issues (I haven't tested the workflows extensively though)

**Review by broeder-j — APPROVED** [review]
After discussion, is_code functionality is now in aiida_core with load_code

**Comment by broeder-j** [comment]
solves issue #120

**Pull request merged**
