### PR TITLE
Spex

### PR DESCRIPTION
**Pull request by broeder-j**
@anoopkcn Do you want this to be merged and released?

### CODE REVIEW

**Comment by anoopkcn** [comment]
Some of the tests failed, let me check them and you can merge it

**Comment by broeder-j** [comment]
What is the difference between your strain workflow and the existing eos workchain?

**Comment by anoopkcn** [comment]
Strain workflow calculates the rate of change of bandgap w.r.t volume of the unit cell. The output dct is different, there is a redundant bulk modulus calculation that can be dropped from the workflow

**Comment by broeder-j** [comment]
But since in the case of the bulk modulus you need the same calculations and calculating the bulk modulus is not expensive would it not make sense to just add that output if it always can be calculated from the usual eos calculations.

**Comment by anoopkcn** [comment]
I think this can be done, When I wrote it I didn't want to make modifications to any original files. But perhaps you can merge everything but the strain workflow and we can think about this later since this workflow is very specific to my project. But other changes are in the pull request are for running `aiida-spex`

**Comment by anoopkcn** [comment]
And I am not sure this quantity can always be calculated

**Comment by broeder-j** [comment]
Because does this only work with a bandgap from the gw mode or why? From the definition a a zero bandgap is fine.

**Comment by anoopkcn** [comment]
The gw mode does not affect the strain workflow, it is strictly DFT, I havn't tested strain workflow for more than 3 scaling points.

**Comment by anoopkcn** [comment]
one has to adapt the calculation of the rate of change beyond a 3 point formula. The theory assumes the change to be linear so in principle, this shouldn't be a problem.

**Comment by broeder-j** [comment]
ah ok. So we merge it for now (since I also assume you have used it, so it should be somewhere). I register this new workchain. But we open an 'documentation' issue on that to discuss possible ways to continue.

thanks for your work!

**Pull request merged**
