### PR TITLE
Add option to set multiple species containing a specified string

### PR DESCRIPTION
**Pull request by janssenhenning**
```set_species``` now accepts ```species_name='all-<string>'``` as input and will apply changes to all species containing ```<string>``` in their name

See issue #87

### CODE REVIEW

**Comment by broeder-j** [comment]
Nice! I did not know about `contains`in xpaths. I will wait till you have added the ldaU tag creation.

**Comment by janssenhenning** [comment]
ldaU tag creation is also added now

**Comment by janssenhenning** [comment]
contains seems to be case sensitive. I tried the test with ```all-fe``` and no changes were made

**Comment by broeder-j** [comment]
> `contains` seems to be case sensitive. I tried the test with `all-fe` and no changes were made

very good, because I thought about things like Os and O (F and Fe), or F and Hf.
because if you have Os and O together you should set something on the O only by using  `species_name='all-O-'`. and due to the case sensitivity, `species_name='all-F'` sets on the F only and not on Hf.

**Review by broeder-j — APPROVED** [review]

**Comment by broeder-j** [comment]
I will merge this now. Thanks @janssenhenning! 
This relates to and solves partly #87

**Pull request merged**
